name: Deploy Nodejs code on ExCloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker Build and Push
        run: |
          docker build -t developerxdemon/chaicode-node .
          docker push developerxdemon/chaicode-node

      - name: Deploy on ExCloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 210.79.129.206
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # cd /home/ubuntu/devops
            cd /home/ubuntu/devops

            # git pull 
            git pull origin main

            # make sure tp pull a fresh copy of developerxdemon/chaicode-node
            sudo docker compose pull

            # docker compose up -d
            sudo docker compose up -d

            # Clean up old/unused images
            sudo docker image prune -f
